import { jsPDF } from "jspdf";
import type { ScreeningResponse, Verdict } from "@/types/screening";

const VERDICT_COLOR: Record<Verdict, [number, number, number]> = {
  Genuine: [16, 185, 129],
  Suspicious: [245, 165, 36],
  Fake: [239, 68, 68],
};

/**
 * Builds and triggers a download of a plain-text PDF inspection report.
 * Deliberately text-only (no embedded document image) — the report is a
 * paper trail of the AI's findings, not a copy of the ID itself, so it
 * doesn't multiply where a scanned government ID photo ends up on disk.
 */
export function exportInspectionReport(result: ScreeningResponse, fileName: string) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const marginX = 48;
  let y = 56;

  doc.setFont("courier", "bold");
  doc.setFontSize(14);
  doc.text("ForensiX AI — Document Inspection Report", marginX, y);
  y += 16;
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.setTextColor(90, 90, 90);
  doc.text("SIH26188 Document Screening System", marginX, y);
  y += 24;

  doc.setDrawColor(200, 200, 200);
  doc.line(marginX, y, 548, y);
  y += 24;

  doc.setTextColor(20, 20, 20);
  doc.setFontSize(10);
  doc.text(`Document ID:   ${result.document_id}`, marginX, y);
  y += 14;
  doc.text(`Source file:   ${fileName}`, marginX, y);
  y += 14;
  doc.text(`Generated:     ${new Date().toISOString()}`, marginX, y);
  y += 28;

  // Verdict block
  const [r, g, b] = VERDICT_COLOR[result.result.verdict] ?? [120, 120, 120];
  doc.setFont("courier", "bold");
  doc.setFontSize(12);
  doc.setTextColor(r, g, b);
  doc.text(`VERDICT: ${result.result.verdict.toUpperCase()}`, marginX, y);
  doc.text(`TRUST SCORE: ${result.result.trust_score}/100`, 320, y);
  y += 20;
  doc.setTextColor(20, 20, 20);
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  for (const line of result.result.explanation) {
    y = wrapLine(doc, `- ${line}`, marginX, y, 500);
  }
  if (result.ela.compression_warning) {
    y += 6;
    doc.setTextColor(180, 120, 10);
    y = wrapLine(doc, `! ${result.ela.forensic_notes}`, marginX, y, 500);
    doc.setTextColor(20, 20, 20);
  }
  y += 20;

  y = sectionHeader(doc, "Extracted Fields (OCR)", marginX, y);
  const fieldEntries = Object.entries(result.ocr.fields);
  if (fieldEntries.length === 0) {
    doc.text("No fields extracted.", marginX, y);
    y += 14;
  } else {
    for (const [key, field] of fieldEntries) {
      doc.text(
        `${key.padEnd(12)}: ${field.value}   (confidence ${(field.confidence * 100).toFixed(0)}%)`,
        marginX,
        y,
      );
      y += 14;
    }
  }
  y += 14;

  y = sectionHeader(doc, "ELA Tamper Analysis", marginX, y);
  doc.text(`Tamper score:        ${result.ela.tamper_score.toFixed(4)}`, marginX, y);
  y += 14;
  doc.text(`Suspicious regions:  ${result.ela.suspicious_regions.length}`, marginX, y);
  y += 14;
  doc.text(`Compression warning: ${result.ela.compression_warning ? "YES" : "no"}`, marginX, y);
  y += 14;
  result.ela.suspicious_regions.forEach((region, i) => {
    doc.text(
      `  [${i + 1}] x=${region.x} y=${region.y} w=${region.width} h=${region.height} err=${region.mean_error.toFixed(2)}`,
      marginX,
      y,
    );
    y += 12;
  });
  y += 14;

  y = sectionHeader(doc, "Face Match", marginX, y);
  doc.text(`Similarity score:       ${(result.face_match.similarity_score * 100).toFixed(1)}%`, marginX, y);
  y += 14;
  doc.text(`Face detected on ID:    ${result.face_match.face_detected_on_id ? "yes" : "no"}`, marginX, y);
  y += 14;
  doc.text(`Face detected on selfie:${result.face_match.face_detected_on_selfie ? " yes" : " no"}`, marginX, y);
  y += 24;

  doc.setFontSize(7.5);
  doc.setTextColor(140, 140, 140);
  doc.text(
    "This report is generated by an automated screening pipeline and is a decision-support aid,",
    marginX,
    770,
  );
  doc.text("not a final determination. Findings should be reviewed by an authorized officer.", marginX, 782);

  doc.save(`inspection-report-${result.document_id.slice(0, 8)}.pdf`);
}

function sectionHeader(doc: jsPDF, title: string, x: number, y: number): number {
  doc.setFont("courier", "bold");
  doc.setFontSize(10);
  doc.setTextColor(20, 20, 20);
  doc.text(title, x, y);
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  return y + 16;
}

function wrapLine(doc: jsPDF, text: string, x: number, y: number, maxWidth: number): number {
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  for (const line of lines) {
    doc.text(line, x, y);
    y += 12;
  }
  return y;
}
